"""
Django settings for drf_template project.

Generated by 'django-admin startproject' using Django 4.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import environ
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
from drf_template.environment import Environment

BASE_DIR = Environment.BASE_DIR
BASE_URL = Environment.BASE_URL

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = Environment.env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = Environment.env('DEBUG') == 'True'
ALLOWED_HOSTS = []

# Application definition
INSTALLED_APPS = [
    'drf_template',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    # 'actstream', # Audit module
    'django_filters',
    'corsheaders',
    'schema_graph',
    'sequences.apps.SequencesConfig',
    'drf_spectacular',

    'apps.authentication',
    'apps.task',
    'apps.app_1',
    'apps.app_2',
    'apps.app_3',
]
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
ROOT_URLCONF = 'drf_template.urls'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
WSGI_APPLICATION = 'drf_template.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': Environment.env('DATABASE_ENGINE'),
        'NAME': Environment.env('DATABASE_NAME'),
        'USER': Environment.env('DATABASE_USER'),
        'PASSWORD': Environment.env('DATABASE_PASSWORD'),
        'HOST': Environment.env('DATABASE_HOST'),
        'PORT': Environment.env('DATABASE_PORT'),
    },
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/
LANGUAGE_CODE = 'en-us'
TIME_ZONE = Environment.env('TIME_ZONE')
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/
STATIC_URL = 'static/'
STATIC_ROOT = 'staticfiles'
STATICFILES_DIRS = []

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
REST_FRAMEWORK = {
    # 'DEFAULT_AUTHENTICATION_CLASSES': (
    #      'ETRM.apps.Authentication.authentication.SecretKeyAuthentication',
    #     # 'ETRM.apps.Authentication.classes.ExpiringTokenAuthentication',  # Custom authentication class
    # ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
        'rest_framework.permissions.DjangoModelPermissions',
    ),
    'DEFAULT_PAGINATION_CLASS': (
        'apps.core.paginations.StandardResultsSetPagination'
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

########################
# API Doc Configuration
########################
SPECTACULAR_SETTINGS = {
    'TITLE': 'API',
    'DESCRIPTION': 'API Description',
    'VERSION': '1.0.0',
}

########################
# Audit Configuration
# If you need to add an auditing or tracking system, you can use the library 'django-activity-stream'.
########################
# ACTSTREAM_SETTINGS = {
#     'MANAGER': 'authentication.managers.audit.AuditManager',
#     'FETCH_RELATIONS': True,
#     'USE_JSONFIELD': True,
# }


########################
# Authentication
########################
# AUTH_USER_MODEL = 'authentication.User' # Variable para cambiar el modelo usado para la autenticacion
AUTHENTICATION_BACKENDS = (
    # 'django.contrib.auth.backends.RemoteUserBackend', # Auth basada en usuario de Windows
    "django.contrib.auth.backends.ModelBackend",  # Auth basada en user/password
)

########################
# LOGGING
########################
LOGGING = Environment.LOGGER_CFG

########################
# CORS
########################
CORS_ORIGIN_ALLOW_ALL = True
# CORS_ORIGIN_WHITELIST = [
#  'http://localhost:80',
# ]
# CORS_ALLOWED_ORIGIN = [
#  'http://localhost:80',
# ]

# SESSION_COOKIE_SAMESITE = None
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
CORS_ALLOW_HEADERS = (
    'accept',
    'accept-encoding',
    'accept-language',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'cache-control',
    'connection',
    'sec-fetch-mode',
    'referer',
    'host',
)
